namespace Personal.Control.Models.Responses
{
    public class UserResponse
    {
        /// <summary>
        /// Id generated by the service for the user
        /// </summary>
        public string Id { get; set; } = string.Empty;
    }
}
