name: format

on:
  push:
    paths:
      - "**.cs"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 7.x

      - name: Install format tool
        run: dotnet tool install -g dotnet-format

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run
        run: dotnet format whitespace "./src/" --folder --verify-no-changes --verbosity diagnostic