name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarScanner for .NET 7 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@v2.2.2
        with:
            # The key of the SonarQube project
            sonarProjectKey: matcastro_Controle-Pessoal
            # The name of the SonarQube project
            sonarProjectName:  Controle-Pessoal
            # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
            sonarOrganization: matcastro

        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
